;-------------------------------------------------------------/ SPRID v2 /---
infoMsg:
DB "SPRID ver. 2.4 * SPRAWDZ NUMER IDENTYFIKACYJNY * Autor: 'marikaz'",13,10
DB 'Program sprawdza pod wzgledem formalnym poprawnosc niektorych',13,10
DB 'numerow seryjnych i ewidencyjnych. Szczegolowe info w README.TXT.',13,10
DB 13,10
DB 9,'SPRID.COM {OPCJE[:]}<ID>',13,10
DB 13,10
DB 'OPCJE:  /A  IBAN (PL)                   /B  ID Banku',13,10
DB '        /D  Dowod Osobisty              /E  EAN (8 lub 13 cyfr)',13,10
DB '        /I  ISBN/ISSN (stare)           /K  Karta Platnicza',13,10
DB "        /L  Alg. Luhn'a (IMEI itp.)     /N  NIP (PL)",13,10
DB '        /P  PESEL                       /R  REGON (9 lub 14 cyfr)',13,10
DB '        /S  Paszport                    /W  Ksiega Wieczysta (nowa)',13,10
DB 13,10
DB '   ID:  Jak w dokumencie.',13,10
DB '        Odstepy nalezy pominac lub zastapic znakiem minus [-].',13,10
DB '$'
